# Generated by Django 4.1.3 on 2022-11-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('sino', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bikemodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sino', models.PositiveIntegerField()),
                ('Bike_model', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('tank_capacity', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('launch_Date', models.CharField(max_length=50)),
                ('description', models.DateField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeStore.bike')),
            ],
        ),
    ]
