# Generated by Django 4.1.3 on 2022-11-17 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_name', models.CharField(max_length=100)),
                ('M_Year', models.DateField()),
                ('Milage', models.CharField(max_length=50)),
                ('Fuel_type', models.CharField(max_length=50)),
                ('Company_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritems.company')),
            ],
        ),
    ]
